name: .NET Test Build

on:
  push:
    branches: main
  pull_request:
    branches: main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  AZURE_WEBAPP_NAME: lewissdev

jobs:
  build-and-test:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: .Net Setup
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: dotnet restore
        run: dotnet restore
        working-directory: ./Lewiss

      - name: build
        run: dotnet build --configuration Release --no-restore
        working-directory: ./Lewiss

      - name: test
        run: dotnet test --configuration Release --no-build
        working-directory: ./Lewiss

  docker-build-push-deploy-azure:
    needs: build-and-test
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5

      - name: Log into Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor}}
          password: ${{ secrets.GITHUB_TOKEN}}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository}}

      - name: Build and Push the Docker image
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v3
        with:
          subject-name: ${{ env.REGISTRY}}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
          
    steps:
      - name: Azure Login
        uses: azure/login@8c334a195cbb38e46038007b304988d888bf676a
        with:
          client-id: ${{secrets.AZURE_CLIENT_ID}}
          tenant-id: ${{secrets.AZURE_TENANT_ID}}
          subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{env.AZURE_WEBAPP_NAME}}
          images: ${{ env.REGISTRY}}/${{ env.IMAGE_NAME}}:${{ steps.push.outputs.digest }}
